build: Upgrade tslib
Needed to solve the following error:

```
 semantic error TS2807: This syntax requires an imported helper named
 '__spreadArray' with 3 parameters, which is not compatible with the one
 in 'tslib'. Consider upgrading your version of 'tslib'.
```